### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by JangoSteve** [alfajango/mobilecan#1]

**Comment by JangoSteve** [comment]
This is probably one of the larger features to demo in terms of scope, so let's hold off on this one until we have a few others done. I'm thinking it'd probably involve some sort of combination of the app cache and local storage features. Here's a StackOverflow post about it, but it's from a few years ago, so there may be a better way to look into nowadays.

http://stackoverflow.com/a/2786567/366381

**Comment by PatrickMcSweeny** [comment]
Lesson 11 in this Udacity course has some good information about offline storage.

https://www.udacity.com/course/mobile-web-development--cs256

**Comment by PatrickMcSweeny** [comment]
Maybe we could do a simple JS game for this one.

**Comment by JangoSteve** [comment]
That'd be pretty cool. How involved do you think a simple JS game would be?

**Comment by PatrickMcSweeny** [comment]
That depends on a lot of things. The easiest route would be to use an open source game with proper attribution. Developing our own could potentially be pretty time consuming.

**Comment by PatrickMcSweeny** [comment]
An easier and less time consuming idea would be to develop a simple shopping list app that someone could update even if there phone is not connected to the internet.
