### ISSUE TITLE
Cause phone to vibrate

### ISSUE THREAD

**Issue by PatrickMcSweeny** [alfajango/mobilecan#16]

**Comment by JangoSteve** [comment]
Let's add an "advanced" demo, which does something cool with modulating vibration duration. E.g. something like vibrating a tune, or converting an text input to morse code, or something else cool like that.

**Comment by JangoSteve** [comment]
Let's also add a note that it may not work on iPhones.

**Comment by PatrickMcSweeny** [comment]
In the latest commit on this issue I added a conditional to see if the vibrate function exists inside the browser.

**Comment by JangoSteve** [comment]
This looks good. Let's see if we can possibly add a stop button as well.
