### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by JangoSteve** [alfajango/mobilecan#2]

**Comment by JangoSteve** [comment]
Here, we'd use the `navigator.geolocation` function in JS:

```
navigator.geolocation.getCurrentPosition(setLocation, locationError)
```

**Comment by JangoSteve** [comment]
One simple idea would be to have the geolocation ask the user to share their location, and then plot their location on an embedded map.

As Patrick pointed out, however, this might not sink in with the user that it's not the native Google Maps app somehow doing it.

Maybe let's do something more like showing them their zip code and possibly even information such as weather for their location, using the open weather API.

**Comment by JangoSteve** [comment]
Looks really good. Some suggestions or things left to do would be:

* Get an API key for the mapping.
* Add a loading indicator when the button has been clicked while the map loads.
* Add a check for if the user denies location access, so the page will say "Location access has been denied".

**Comment by JangoSteve** [comment]
This looks great. The only other thing I'd say let's see if we can add here would be reverse-geocoding the lat/long location to get the nearest address. Let's see if we can build in an API endpoint such as this to get the nearest address:

http://www.geonames.org/maps/us-reverse-geocoder.html#findNearestAddress

(here's the JSON endpoint for the above API):

http://api.geonames.org/findNearestAddressJSON?lat=42.2926624&lng=-83.7347557&username=demo

Google also has an API for this as well if we want to use that instead:

https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse

**Comment by PatrickMcSweeny** [comment]
The geonames API is only sort of accurate when giving your current address via reverse geocoding and when I tried the Google one, it just tells you what neighborhood you are in. I think it would be best to just leave it using the map.

**Comment by JangoSteve** [comment]
OK, that's fine for now.
