### ISSUE TITLE
Local storage

### ISSUE THREAD

**Issue by JangoSteve** [alfajango/mobilecan#7]

**Comment by JangoSteve** [comment]
This might overlap with the offline mode ticket #1, so not sure if this needs its own page or not. But it could work differently in that we could allow visitors to type some information or something like that, and then save it to local storage, so when they come back later, it's still there.

But I'm sure we could probably come up with something with a bit more pizazz.

**Comment by PatrickMcSweeny** [comment]
My idea for a simple shopping list app for #1 could cover this issue as well.
